spring:
  application:
    name: remote-falcon-plugins-api
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080

info:
  build:
    artifact: remote-falcon-plugins-api

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "OPTIONS, GET, POST, PUT, DELETE"
        allowed-headers: "*"

logging:
  level:
    org:
      springframework:
        graphql: OFF #Turn off logging for Spring GraphQL

sequence-limit: 200