name: Sync Fork and Build Docker Image

on:
  schedule:
    - cron: '12 * * * *'  # every hour (adjust as needed)
  workflow_dispatch:

env:
  GHCR_NAMESPACE: ne0n09
  UPSTREAM_REPO: https://github.com/Remote-Falcon/remote-falcon-plugins-api.git 

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      synced: ${{ steps.push_changes.outputs.pushed }}

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add upstream remote
        run: git remote add upstream ${{ env.UPSTREAM_REPO }}

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push changes if any
        id: push_changes
        run: |
          if git diff --quiet; then
            echo "::set-output name=pushed::false"
          else
            git push origin main
            echo "::set-output name=pushed::true"
          fi

  build:
    needs: sync
    if: needs.sync.outputs.synced == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

          SHORT_SHA=${GITHUB_SHA::7}
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

          DATE_TAG=$(date +'%Y%m%d')
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:latest
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.date_tag }}
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
