name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  GHCR_NAMESPACE: ne0n09  # Change to your GHCR username or org here

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set variables
        id: vars
        run: |
          # Lowercase repo name only (no owner)
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT

          # Short SHA for tagging
          SHORT_SHA=${GITHUB_SHA::7}
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

          # Date tag YYYYMMDD
          DATE_TAG=$(date +'%Y.%m.%d')
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:latest
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.date_tag }}
            ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ steps.vars.outputs.repo_name }}:${{ steps.vars.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
