name: Sync, Build, and Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 00:00 CST

env:
  ORIGINAL_OWNER: Ne0n09                     # Upstream owner
  ORIGINAL_REPO: remote-falcon-plugins-api   # Upstream repo
  GHCR_NAMESPACE: sh-rf                      # Your GHCR namespace (lowercase)
  IMAGE_NAME: ghcr.io/ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.ORIGINAL_REPO }}

jobs:
  sync-build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/${{ env.ORIGINAL_OWNER }}/${{ env.ORIGINAL_REPO }}.git

      - name: Fetch upstream changes
        run: git fetch upstream main

      - name: Merge upstream changes into fork
        id: merge
        run: |
          set +e
          git merge upstream/main --no-edit
          MERGE_STATUS=$?
          set -e
          echo "merge_status=$MERGE_STATUS" >> $GITHUB_OUTPUT

      - name: Handle merge conflicts (create PR)
        if: steps.merge.outputs.merge_status != '0'
        run: |
          echo "❌ Merge conflict detected. Creating PR..."
          BRANCH="sync-$(date +'%Y%m%d%H%M%S')"
          git merge --abort
          git checkout -b "$BRANCH"
          git fetch upstream
          git merge upstream/main || true
          git push origin "$BRANCH"
          gh pr create \
            --title "Sync from upstream" \
            --body "Automatic PR to sync with upstream changes." \
            --base main \
            --head "$BRANCH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Commit sync if upstream has changes
        if: steps.merge.outputs.merge_status == '0'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -am "Sync from upstream"
            git push origin main
          else
            echo "✅ No upstream changes. Exiting."
            exit 0
          fi

      - name: Generate version tags
        if: steps.merge.outputs.merge_status == '0'
        id: version
        run: |
          TZ=America/Chicago
          DATE_TAG=$(date +'%Y.%m.%d')
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "date_tag=$DATE_TAG" >> $GITHUB_OUTPUT
          echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.check.outputs.has_changes == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.check.outputs.has_changes == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with cache
        if: steps.check.outputs.has_changes == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.date_tag }}
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        if: steps.merge.outputs.merge_status == '0'
        run: |
          COMMITS=$(git log origin/main ^upstream/main --pretty=format:"- %s (%h)")
          gh release create "${{ steps.version.outputs.date_tag }}" \
            --title "Release ${{ steps.version.outputs.date_tag }}" \
            --notes "$COMMITS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
